databases:
  - name: synonyms_api
    databaseName: synonyms_api
    user: synonyms_api

services:
  - type: web
    name: synonyms_api
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: synonyms_api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false